### ISSUE TITLE
china command

### ISSUE THREAD

**Issue by Spit-fires** [PixelPizza/Bot#372]
**Is your feature request related to a problem? Please describe.**
i hate when no china cmd

**Describe the solution you'd like**
add china cmd

**Describe alternatives you've considered**
theres none
**Additional context**

**Comment by JaronZ** [comment]
Make it yourself if you want it that badly

**Comment by JaronZ** [comment]
Thanks @mcpsbot, those are the right labels... no offense @Spit-fires it's just not really important...

**Comment by JaronZ** [comment]
test
